# Base config mimicking our MIDL2020 submission, due to the image size the length is 8 and batch size 1
# Added instance norm
# Only train on 4x
# Not sharing of parameters
# Less filters (96 rather than 128) due to OOM
physics:
    forward_operator: fft2
    backward_operator: ifft2
training:
    datasets:
        # Two datasets, only difference is the shape, so the data can be collated for larger batches
        -   name: FastMRI
            transforms:
                crop: null
                estimate_sensitivity_maps: true  # Estimate the sensitivity map on the ACS
                scaling_key: masked_kspace  # Compute the image normalization based on the masked_kspace maximum
                image_center_crop: false
                masking:
                    name: FastMRIEquispaced
                    accelerations: [4]
                    center_fractions: [0.08]
    batch_size: 1  # This is the batch size per GPU!
    optimizer: Adam
    lr: 0.0001
    weight_decay: 0.0
    lr_step_size: 150000
    lr_gamma: 0.2
    lr_warmup_iter: 1000
    num_iterations: 1000000
    gradient_steps: 1
    gradient_clipping: 0.0
    gradient_debug: false
    checkpointer:
        checkpoint_steps: 1000
    validation_steps: 17000
    loss:
        crop: header
        losses:
            -   function: l1_loss
                multiplier: 1.0
            -   function: ssim_loss
                multiplier: 1.0
validation:
    datasets:
        # Twice the same dataset but a different acceleration factor
        -   name: FastMRI
            regex_filter: ^.*file_brain_AXT1POST_\d{3}_\d{7}.*.h5$
            transforms:
                crop: null
                estimate_sensitivity_maps: true
                scaling_key: masked_kspace
                masking:
                    name: FastMRIEquispaced
                    accelerations: [4]
                    center_fractions: [0.08]
            text_description: 4x/T1POST  # Description for logging
        -   name: FastMRI
            regex_filter: ^.*file_brain_AX(T1|T1PRE)_\d{3}_\d{7}.*.h5$
            transforms:
                crop: null
                estimate_sensitivity_maps: true
                scaling_key: masked_kspace
                masking:
                    name: FastMRIEquispaced
                    accelerations: [4]
                    center_fractions: [0.08]
            text_description: 4x/T1
        -   name: FastMRI
            regex_filter: ^.*file_brain_AXT2_\d{3}_\d{7}.*.h5$
            transforms:
                crop: null
                estimate_sensitivity_maps: true
                scaling_key: masked_kspace
                masking:
                    name: FastMRIEquispaced
                    accelerations: [4]
                    center_fractions: [0.08]
            text_description: 4x/T2
        -   name: FastMRI
            regex_filter: ^.*file_brain_AXFLAIR_\d{3}_\d{7}.*.h5$
            transforms:
                crop: null
                estimate_sensitivity_maps: true
                scaling_key: masked_kspace
                masking:
                    name: FastMRIEquispaced
                    accelerations: [4]
                    center_fractions: [0.08]
            text_description: 4x/FLAIR
    crop: header  # This sets the cropping for the output
    metrics:  # These are obtained from direct.functionals
        - fastmri_psnr
        - fastmri_ssim
        - fastmri_nmse
model:
    model_name: rim.rim.RIM
    hidden_channels: 96
    image_initialization: sense  # This uses the computed sensitivity map to create a zero-filled reconstruction
    length: 8
    depth: 2
    steps: 1
    no_parameter_sharing: true
    instance_norm: true
    dense_connect: false
    replication_padding: true
additional_models:
    sensitivity_model:
        model_name: unet.unet_2d.UnetModel2d
        in_channels: 2
        out_channels: 2
        num_filters: 8
        num_pool_layers: 4
        dropout_probability: 0.0
logging:
    tensorboard:
        num_images: 4
inference:
    batch_size: 8
    dataset:
        name: FastMRI
        text_description: inference
        transforms:
            crop: null
            estimate_sensitivity_maps: true
            scaling_key: masked_kspace
