physics:
    # Modality specific functions, for MRI you need to define the (torch) forward projector here.
    forward_operator: fft2
    backward_operator: ifft2
training:
    datasets:
        -   name: FastMRI
            lists:
                - ../lists/train/512_234/FLAIR/1.5T/16/train.lst
                - ../lists/train/512_234/FLAIR/1.5T/20/train.lst
                - ../lists/train/512_214/FLAIR/1.5T/16/train.lst
                - ../lists/train/512_214/FLAIR/1.5T/18/train.lst
                - ../lists/train/512_234/FLAIR/3T/4/train.lst
                - ../lists/train/512_213/FLAIR/3T/4/train.lst
                - ../lists/train/512_276/FLAIR/3T/4/train.lst
                - ../lists/train/512_234/FLAIR/3T/6/train.lst
                - ../lists/train/512_276/FLAIR/3T/5/train.lst
                - ../lists/train/512_320/FLAIR/1.5T/16/train.lst
                - ../lists/train/512_320/FLAIR/1.5T/20/train.lst
                - ../lists/train/512_320/FLAIR/1.5T/12/train.lst
                - ../lists/train/512_256/FLAIR/1.5T/16/train.lst
                - ../lists/train/640_320/FLAIR/3T/22/train.lst
                - ../lists/train/640_320/FLAIR/3T/24/train.lst
                - ../lists/train/640_320/FLAIR/1.5T/16/train.lst
                - ../lists/train/640_320/FLAIR/1.5T/20/train.lst
                - ../lists/train/640_320/FLAIR/3T/16/train.lst
                - ../lists/train/640_320/FLAIR/3T/20/train.lst
                - ../lists/train/640_320/FLAIR/3T/12/train.lst
                - ../lists/train/640_320/FLAIR/3T/14/train.lst
                - ../lists/train/640_320/FLAIR/3T/8/train.lst
                - ../lists/train/640_320/FLAIR/3T/2/train.lst
                - ../lists/train/640_264/FLAIR/1.5T/24/train.lst
                - ../lists/train/640_264/FLAIR/1.5T/16/train.lst
                - ../lists/train/640_264/FLAIR/1.5T/18/train.lst
                - ../lists/train/640_264/FLAIR/1.5T/20/train.lst
                - ../lists/train/640_312/FLAIR/1.5T/16/train.lst
                - ../lists/train/640_312/FLAIR/1.5T/20/train.lst
                - ../lists/train/640_262/FLAIR/3T/16/train.lst
                - ../lists/train/640_262/FLAIR/3T/20/train.lst
                - ../lists/train/640_274/FLAIR/3T/16/train.lst
                - ../lists/train/640_274/FLAIR/3T/20/train.lst
                - ../lists/train/640_298/FLAIR/3T/20/train.lst
                - ../lists/train/640_264/FLAIR/1.5T/12/train.lst
                - ../lists/train/640_262/FLAIR/3T/12/train.lst
            transforms:
                crop: null
                crop_type: gaussian
                estimate_sensitivity_maps: true
                sensitivity_maps_gaussian: null
                scaling_key: masked_kspace
                image_center_crop: false
                masking:
                    name: FastMRIEquispaced
                    accelerations: [4]
                    center_fractions: [0.08]
    batch_size: 1
    optimizer: Adam
    lr: 0.0001
    weight_decay: 0.0
    lr_step_size: 10000
    lr_gamma: 0.5
    lr_warmup_iter: 1000
    num_iterations: 1000000
    gradient_steps: 1
    gradient_clipping: 0.0
    gradient_debug: false
    checkpointer:
        checkpoint_steps: 2000
    validation_steps: 2000
    loss:
        crop: null
        losses:
            -   function: ssim_loss
                multiplier: 1.0
validation:
    batch_size: 4
    datasets:
        # Twice the same dataset but a different acceleration factor
        -   name: FastMRI
            lists:
                - ../lists/val/512_214/FLAIR/1.5T/16/val.lst
                - ../lists/val/512_234/FLAIR/1.5T/16/val.lst
                - ../lists/val/640_264/FLAIR/1.5T/16/val.lst
                - ../lists/val/512_320/FLAIR/1.5T/20/val.lst
                - ../lists/val/512_234/FLAIR/1.5T/20/val.lst
                - ../lists/val/640_264/FLAIR/1.5T/20/val.lst
                - ../lists/val/640_320/FLAIR/1.5T/20/val.lst
            text_description: 1.5T_4x  # Description for logging
            transforms:
                crop: null
                estimate_sensitivity_maps: true
                sensitivity_maps_gaussian: null
                scaling_key: masked_kspace
                image_center_crop: true
                masking:
                    name: FastMRIEquispaced
                    accelerations: [4]
                    center_fractions: [0.08]
        -   name: FastMRI
            lists:
                - ../lists/val/640_320/FLAIR/3T/20/val.lst
                - ../lists/val/640_320/FLAIR/3T/18/val.lst
                - ../lists/val/640_262/FLAIR/3T/16/val.lst
                - ../lists/val/640_320/FLAIR/3T/16/val.lst
                - ../lists/val/640_320/FLAIR/3T/14/val.lst
                - ../lists/val/640_320/FLAIR/3T/12/val.lst
                - ../lists/val/512_276/FLAIR/3T/6/val.lst
                - ../lists/val/512_276/FLAIR/3T/5/val.lst
                - ../lists/val/512_276/FLAIR/3T/4/val.lst
                - ../lists/val/512_213/FLAIR/3T/4/val.lst
            text_description: 3T_4x  # Description for logging
            transforms:
                crop: null
                estimate_sensitivity_maps: true
                sensitivity_maps_gaussian: null
                scaling_key: masked_kspace
                image_center_crop: true
                masking:
                    name: FastMRIEquispaced
                    accelerations: [4]
                    center_fractions: [0.08]
    crop: header
    metrics:
        - fastmri_psnr
        - fastmri_ssim
        - fastmri_nmse
model:
    model_name: rim.rim.RIM
    hidden_channels: 128
    length: 8
    depth: 2
    steps: 1
    no_parameter_sharing: false
    instance_norm: false
    dense_connect: false
    replication_padding: true
    image_initialization: sense
    learned_initializer: true
    initializer_channels: [32, 32, 64, 64]
    initializer_dilations: [1, 1, 2, 4]
    initializer_multiscale: 1
additional_models:
    sensitivity_model:
        model_name: unet.unet_2d.UnetModel2d
        in_channels: 2
        out_channels: 2
        num_filters: 8
        num_pool_layers: 4
        dropout_probability: 0.0
tensorboard:
    num_images: 4
inference:
    dataset:
        name: FastMRI
        pass_mask: true
        transforms:
            crop: null
            scaling_key: masked_kspace
            estimate_sensitivity_maps: true
            sensitivity_maps_gaussian: null
