# Higher LR than the one without _2
physics:
    forward_operator: fft2
    backward_operator: ifft2
training:
    datasets:
        -   name: FastMRI
            lists:
                - ../lists/train/640_256/T2/1.5T/4/train.lst
                - ../lists/train/640_272/T2/1.5T/16/train.lst
                - ../lists/train/640_272/T2/1.5T/20/train.lst
                - ../lists/train/640_320/T2/1.5T/2/train.lst
                - ../lists/train/640_320/T2/1.5T/4/train.lst
                - ../lists/train/640_320/T2/1.5T/5/train.lst
                - ../lists/train/640_320/T2/1.5T/6/train.lst
                - ../lists/train/640_320/T2/1.5T/8/train.lst
                - ../lists/train/640_320/T2/1.5T/10/train.lst
                - ../lists/train/640_320/T2/1.5T/12/train.lst
                - ../lists/train/640_320/T2/1.5T/16/train.lst
                - ../lists/train/640_320/T2/1.5T/18/train.lst
                - ../lists/train/640_320/T2/1.5T/20/train.lst
                - ../lists/train/640_320/T2/1.5T/24/train.lst
                - ../lists/train/768_324/T2/3T/12/train.lst
                - ../lists/train/768_324/T2/3T/14/train.lst
                - ../lists/train/768_396/T2/3T/12/train.lst
                - ../lists/train/768_396/T2/3T/14/train.lst
                - ../lists/train/768_324/T2/3T/16/train.lst
                - ../lists/train/768_342/T2/3T/16/train.lst
                - ../lists/train/768_396/T2/3T/16/train.lst
                - ../lists/train/768_396/T2/3T/18/train.lst
                - ../lists/train/768_396/T2/3T/20/train.lst
                - ../lists/train/768_396/T2/3T/28/train.lst
                - ../lists/train/768_392/T2/3T/4/train.lst
                - ../lists/train/768_396/T2/3T/2/train.lst
                - ../lists/train/768_396/T2/3T/8/train.lst
                - ../lists/train/768_308/T2/3T/4/train.lst
            transforms:
                crop: null
                crop_type: gaussian
                estimate_sensitivity_maps: true
                sensitivity_maps_gaussian: null
                scaling_key: masked_kspace
                image_center_crop: false
                masking:
                    name: FastMRIEquispaced
                    accelerations: [4]
                    center_fractions: [0.08]
    batch_size: 1
    optimizer: Adam
    lr: 0.00033
    weight_decay: 0.0
    lr_step_size: 20000
    lr_gamma: 0.5
    lr_warmup_iter: 1000
    num_iterations: 1000000
    gradient_steps: 1
    gradient_clipping: 0.0
    gradient_debug: false
    checkpointer:
        checkpoint_steps: 500 # against oom
    validation_steps: 2000
    loss:
        crop: null
        losses:
            -   function: ssim_loss
                multiplier: 1.0
validation:
    batch_size: 4
    datasets:
        # Twice the same dataset but a different acceleration factor
        -   name: FastMRI
            lists:
                - ../lists/val/640_240/T2/1.5T/20/val.lst
                - ../lists/val/640_272/T2/1.5T/4/val.lst
                - ../lists/val/640_272/T2/1.5T/16/val.lst
                - ../lists/val/640_272/T2/1.5T/20/val.lst
                - ../lists/val/640_320/T2/1.5T/4/val.lst
                - ../lists/val/640_320/T2/1.5T/5/val.lst
                - ../lists/val/640_320/T2/1.5T/6/val.lst
                - ../lists/val/640_320/T2/1.5T/8/val.lst
                - ../lists/val/640_320/T2/1.5T/10/val.lst
                - ../lists/val/640_320/T2/1.5T/12/val.lst
                - ../lists/val/640_320/T2/1.5T/16/val.lst
                - ../lists/val/640_320/T2/1.5T/18/val.lst
                - ../lists/val/640_320/T2/1.5T/20/val.lst
            text_description: 1.5T_4x  # Description for logging
            transforms:
                crop: null
                estimate_sensitivity_maps: true
                sensitivity_maps_gaussian: null
                scaling_key: masked_kspace
                image_center_crop: true
                masking:
                    name: FastMRIEquispaced
                    accelerations: [4]
                    center_fractions: [0.08]
        -   name: FastMRI
            lists:
                - ../lists/val/768_396/T2/3T/10/val.lst
                - ../lists/val/768_396/T2/3T/12/val.lst
                - ../lists/val/768_396/T2/3T/14/val.lst
                - ../lists/val/768_396/T2/3T/16/val.lst
                - ../lists/val/768_396/T2/3T/18/val.lst
                - ../lists/val/768_396/T2/3T/20/val.lst
                - ../lists/val/768_392/T2/3T/4/val.lst
                - ../lists/val/768_350/T2/3T/4/val.lst
                - ../lists/val/768_324/T2/3T/12/val.lst
                - ../lists/val/768_396/T2/3T/16/val.lst
            text_description: 3T_4x  # Description for logging
            transforms:
                crop: null
                estimate_sensitivity_maps: true
                sensitivity_maps_gaussian: null
                scaling_key: masked_kspace
                image_center_crop: true
                masking:
                    name: FastMRIEquispaced
                    accelerations: [4]
                    center_fractions: [0.08]
    crop: header
    metrics:
        - fastmri_psnr
        - fastmri_ssim
        - fastmri_nmse
model:
    model_name: rim.rim.RIM
    hidden_channels: 128
    length: 8
    depth: 2
    steps: 1
    no_parameter_sharing: false
    instance_norm: false
    dense_connect: false
    image_initialization: sense
    replication_padding: true
    learned_initializer: true
    initializer_channels: [32, 32, 64, 64]
    initializer_dilations: [1, 1, 2, 4]
    initializer_multiscale: 1
additional_models:
    sensitivity_model:
        model_name: unet.unet_2d.UnetModel2d
        in_channels: 2
        out_channels: 2
        num_filters: 8
        num_pool_layers: 4
        dropout_probability: 0.0
tensorboard:
    num_images: 4
inference:
    dataset:
        name: FastMRI
        transforms:
            crop: null
            estimate_sensitivity_maps: true
            sensitivity_maps_gaussian: null
            scaling_key: masked_kspace
            masking:
                name: FastMRIEquispaced
                accelerations: [4]
                center_fractions: [0.08]
